# Generated by Django 5.1.3 on 2024-11-19 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='administered_leagues', to=settings.AUTH_USER_MODEL, verbose_name='Administrators'),
        ),
        migrations.AddField(
            model_name='league',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leagues', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
