# Generated by Django 5.1.3 on 2024-11-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_administrators_league_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='governing_body',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Governing Body'),
        ),
        migrations.AlterField(
            model_name='league',
            name='sanctioning_body',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sanctioning Body'),
        ),
    ]
