# Generated by Django 5.1.6 on 2025-02-14 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0004_category_alter_league_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="derogation_athletes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Athletes participating under derogation",
                related_name="derogation_leagues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="ruleset_config",
            field=models.JSONField(
                default=dict,
                help_text="Custom configuration for the ruleset",
                verbose_name="ruleset configuration",
            ),
        ),
        migrations.AddField(
            model_name="league",
            name="ruleset_type",
            field=models.CharField(
                choices=[("IFSC", "IFSC Rules"), ("FQME", "FQME Rules")],
                default="IFSC",
                max_length=50,
                verbose_name="ruleset type",
            ),
        ),
        migrations.AddField(
            model_name="leagueranking",
            name="original_points",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="original points before derogation"
            ),
        ),
        migrations.AddField(
            model_name="leagueranking",
            name="original_ranking",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="original ranking before derogation"
            ),
        ),
        migrations.AddField(
            model_name="leagueranking",
            name="points_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Athlete whose points were redistributed to this athlete",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points_beneficiary",
                to="leagues.leagueranking",
            ),
        ),
    ]
