# Generated by Django 5.1.3 on 2024-11-11 03:53

from django.db import migrations

def create_default_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    
    # Create default roles
    default_roles = [
        {
            'name': 'Admin',
            'description': 'Full system access'
        },
        {
            'name': 'Technical Delegate',
            'description': 'Can manage competitions and results'
        },
        {
            'name': 'Judge',
            'description': 'Can input scores and manage competition events'
        },
        {
            'name': 'Athlete',
            'description': 'Can participate in competitions'
        }
    ]
    
    for role_data in default_roles:
        Role.objects.get_or_create(
            name=role_data['name'],
            defaults={'description': role_data['description']}
        )

def reverse_func(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Role.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),  # Make sure this matches your initial migration
    ]

    operations = [
        migrations.RunPython(create_default_roles, reverse_func),
    ]
