# Generated by Django 5.1.6 on 2025-02-14 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.JSONField(default=list, verbose_name='certifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.JSONField(blank=True, null=True, verbose_name='emergency contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_info',
            field=models.JSONField(blank=True, null=True, verbose_name='medical information'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=models.JSONField(default=dict, verbose_name='notification settings'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(default=dict, verbose_name='user preferences'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, verbose_name='profile picture URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(default=list, verbose_name='user roles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='action')),
                ('details', models.JSONField(verbose_name='action details')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user audit log',
                'verbose_name_plural': 'user audit logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
