# Generated by Django 5.1.6 on 2025-02-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options_remove_user_phone_number_user_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="certifications",
            field=models.JSONField(
                default=list, null=True, verbose_name="certifications"
            ),
        ),
    ]
