# Generated by Django 5.1.6 on 2025-02-14 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gym",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="gym",
            name="description",
        ),
        migrations.AddField(
            model_name="gym",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="climbing_areas",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gym",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="contact_info",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="gym",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="facilities",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gym",
            name="operating_hours",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gymmembership",
            name="membership_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="membership type"
            ),
        ),
        migrations.AlterField(
            model_name="gymmembership",
            name="payment_status",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="payment status"
            ),
        ),
        migrations.AlterField(
            model_name="gymmembership",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="gymstaff",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="position"
            ),
        ),
        migrations.AlterField(
            model_name="gymstaff",
            name="responsibilities",
            field=models.JSONField(default=dict, verbose_name="responsibilities"),
        ),
        migrations.AlterField(
            model_name="gymstaff",
            name="schedule",
            field=models.JSONField(default=dict, verbose_name="work schedule"),
        ),
        migrations.AlterField(
            model_name="gymstaff",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="area_affected",
            field=models.JSONField(default=dict, verbose_name="affected area"),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="date_performed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date performed"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="duration"),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="maintenance_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="maintenance type"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="color",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="color"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="grade",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="grade"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="location",
            field=models.JSONField(default=dict, verbose_name="location in gym"),
        ),
        migrations.AlterField(
            model_name="route",
            name="set_date",
            field=models.DateField(blank=True, null=True, verbose_name="set date"),
        ),
        migrations.AddIndex(
            model_name="gym",
            index=models.Index(fields=["city"], name="gyms_gym_city_e7449d_idx"),
        ),
        migrations.AddIndex(
            model_name="gym",
            index=models.Index(fields=["country"], name="gyms_gym_country_9eab66_idx"),
        ),
        migrations.AddIndex(
            model_name="gym",
            index=models.Index(
                fields=["is_active"], name="gyms_gym_is_acti_0fa45a_idx"
            ),
        ),
    ]
