# Generated by Django 5.1.6 on 2025-02-14 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0003_appeal_event_competitionregistration_athlete_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Administrator"),
                            ("Technical Delegate", "Technical Delegate"),
                            ("Route Setter", "Route Setter"),
                            ("Judge", "Judge"),
                            ("Safety Officer", "Safety Officer"),
                            ("Medical Staff", "Medical Staff"),
                        ],
                        max_length=50,
                        verbose_name="role",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="assigned at"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="competitions.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "competition staff",
                "verbose_name_plural": "competition staff",
                "ordering": ["competition", "role"],
                "unique_together": {("competition", "user", "role")},
            },
        ),
    ]
