# Generated by Django 5.1.6 on 2025-02-16 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_competitionstaff"),
        ("leagues", "0005_league_derogation_athletes_league_ruleset_config_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competitionresult",
            options={
                "ordering": ["category", "round", "ranking"],
                "verbose_name": "competition result",
                "verbose_name_plural": "competition results",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("order", models.IntegerField(verbose_name="order")),
                (
                    "number_of_problems",
                    models.IntegerField(verbose_name="number of problems"),
                ),
                (
                    "time_limit",
                    models.IntegerField(verbose_name="time limit in minutes"),
                ),
                ("format", models.CharField(max_length=50, verbose_name="format")),
                (
                    "rules",
                    models.JSONField(default=dict, verbose_name="round specific rules"),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "round",
                "verbose_name_plural": "rounds",
                "ordering": ["competition", "order"],
                "unique_together": {("competition", "name")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="competitionresult",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="competitionresult",
            name="round",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="competitions.round",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="competitionresult",
            unique_together={("competition", "athlete", "category", "round")},
        ),
    ]
